### ISSUE TITLE
Investigate if result_large_err needs fixing

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#165]

**Comment by abright** [comment]
It does consume memory at least, as there needs to be enough allocated to contain anything within the `Result`. The `InsuffiicientAllowance` one broke once we started using nightly builds after Nov. 23rd. Not sure what changed with it exactly - did the `Address` or `TokenAmount` get bigger due to a change in one of the primitive types they use, or did someone change the limit for that lint.

With the way our error types are set up it is going to affect a lot of functions that will never see that error case.

In the case of `InsuffiicientAllowance` here's a couple things I think would fix it:
1. `Box` it so we only incur that cost when actually using that error
2. Remove anything we don't need - owner/operator addresses should be known to the caller, so removing them shouldn't really hurt anything?
