### ISSUE TITLE
Benchmark revert strategies

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#61]
For reverting state after hook call, benchmark the following strategies

# Clone and Restore
1. Clone state in memory
2. Make changes
3. Flush
4. Call Hook
5. Restore cloned state in memory
6. Flush

# Reload from Cid
1. Store Cid
2. Make changes
3. Flush
4. Call Hook
5. Reload from Cid into memory

**Comment by abright** [comment]
Haven't benchmarked it, but I'm in favour of the reload approach as it can also work in the other direction - to bring us up to date when the state has changed due to re-entrant calls or the like.

I've been experimenting with this a bit in #103 because some of the test cases I'm implementing involve transferring or burning tokens immediately upon receipt (calling transfer or burn from within the receiver hook), which will update the state beyond what the original mint/transfer operation did before it called the receiver hook. Reloading at that point allows the token actor to carry on with the proper state and to provide the most up to date return data instead of a snapshot from when the hook was called.
